### ISSUE TITLE
请问一下，dataset/SegTHOR.py里面的问题

### ISSUE THREAD

**Issue by zz10001** [FENGShuanglang/SegTHOR-Pytorch#4]
如题，它这个https://github.com/FENGShuanglang/SegTHOR-Pytorch/blob/2abc0be3784b906a1a811a3470f5c178c38bd8d0/UNet/dataset/SegTHOR.py#L72
里面的.split('/')[-2]是什么作用的。还有一个问题就是，如果它们想等了，不就相当于img_pre=img_cur那后面的img_pre=img_cur是什么意思

**Comment by Bingo-Zuo** [comment]
> 如题，它这个
> 
> https://github.com/FENGShuanglang/SegTHOR-Pytorch/blob/2abc0be3784b906a1a811a3470f5c178c38bd8d0/UNet/dataset/SegTHOR.py#L72
> 
> 里面的.split('/')[-2]是什么作用的。还有一个问题就是，如果它们想等了，不就相当于img_pre=img_cur那后面的img_pre=img_cur是什么意思

您好，我也有这样的疑问，请问解决了吗？
